---
- name: all child playbooks
  hosts: all
  become: yes
  tasks:
    - name: call child playbook
      include_tasks: "{{item}}"
      with_items:
          - child_install.yml
          - child_start.yml
          - child_copy.yml
          - child_restart.yml